version: '3'

services:
  web:
    build: . 
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
  redis:
    image: redis:latest
  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - solr_core:/opt/solr/server/solr/app

volumes:
  solr_core:
  gem_cache:
