name: Deploy to production namespace

on:
  workflow_run:
    workflows: [ 'Build latest from master' ]
    types: [ 'completed' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ secrets.HATCHER_CLUSTER_CA }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=https://hatcher.kubernetes.lib.umich.edu
        kubectl config set-credentials default --token=`echo ${{ secrets.HATCHER_PRODUCTION_TOKEN }} | base64 -d`
        kubectl config set-context default --cluster=cluster --user=default --namespace=tracc-production
        kubectl config use-context default
    - name: Automatic Deploy
      run: kubectl set image deployment fdtool-web web=docker.pkg.github.com/mlibrary/tracc/tracc-web:${{ github.sha }}
